# Generated by Django 5.2.8 on 2025-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('lost_pet_matched', 'Lost Pet Matched'), ('pet_approved', 'Pet Approved'), ('pet_adopted', 'Pet Adopted'), ('new_message', 'New Chat Message'), ('admin_announcement', 'Admin Announcement'), ('adoption_approved', 'Adoption Approved'), ('adoption_rejected', 'Adoption Rejected'), ('pet_verified', 'Pet Verified')], max_length=50)),
                ('link_target', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
