# Generated by Django 5.2.8 on 2025-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Under Treatment', 'Under Treatment'), ('Recovering', 'Recovering'), ('Chronic Condition', 'Chronic Condition'), ('Critical', 'Critical')], default='Healthy', help_text='Current health status of the pet', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('vaccination_status', models.CharField(choices=[('Up to Date', 'Up to Date'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Not Vaccinated', 'Not Vaccinated'), ('Unknown', 'Unknown')], default='Unknown', help_text='Vaccination status', max_length=50)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('next_vaccination_due', models.DateField(blank=True, null=True)),
                ('vaccination_notes', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions and treatments', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications and dosages', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic health conditions', null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('veterinarian_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_spayed_neutered', models.BooleanField(default=False)),
                ('spay_neuter_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('next_checkup_due', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adoption_status', models.CharField(choices=[('Available for Adoption', 'Available for Adoption'), ('Adopted', 'Adopted'), ('Pending', 'Pending'), ('Lost', 'Lost'), ('Found', 'Found'), ('Reunited', 'Reunited')], default='Available for Adoption', max_length=50)),
                ('tag_registration_number', models.CharField(blank=True, help_text='Tag ID, Registration Number, or License Number', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('location_map_url', models.URLField(blank=True, help_text='Google Maps or other map service URL', null=True)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cloudinary_url', models.URLField(blank=True, help_text='Cloudinary URL for the main image', null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public_id for the main image', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('views_count', models.IntegerField(default=0)),
                ('current_location_type', models.CharField(blank=True, choices=[('user', 'With User'), ('shelter', 'In Shelter'), ('volunteer', 'With Volunteer')], max_length=20, null=True)),
                ('current_location_id', models.IntegerField(blank=True, help_text='ID of shelter or user holding the pet', null=True)),
                ('found_date', models.DateTimeField(blank=True, help_text='When the pet was found', null=True)),
                ('days_in_care', models.IntegerField(default=0, help_text='Days since found')),
                ('owner_consent_for_adoption', models.BooleanField(default=False, help_text="Original finder's consent for adoption")),
                ('moved_to_adoption', models.BooleanField(default=False)),
                ('moved_to_adoption_date', models.DateTimeField(blank=True, null=True)),
                ('is_reunited', models.BooleanField(default=False)),
                ('reunited_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pets/gallery/')),
                ('cloudinary_url', models.URLField(blank=True, help_text='Cloudinary URL for this image', null=True)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public_id for this image', max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
