# Generated by Django 5.2.8 on 2025-12-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='current_location_id',
            field=models.IntegerField(blank=True, help_text='ID of shelter or user holding the pet', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='current_location_type',
            field=models.CharField(blank=True, choices=[('user', 'With User'), ('shelter', 'In Shelter'), ('volunteer', 'With Volunteer')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='days_in_care',
            field=models.IntegerField(default=0, help_text='Days since found'),
        ),
        migrations.AddField(
            model_name='pet',
            name='found_date',
            field=models.DateTimeField(blank=True, help_text='When the pet was found', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_reunited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='moved_to_adoption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pet',
            name='moved_to_adoption_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner_consent_for_adoption',
            field=models.BooleanField(default=False, help_text="Original finder's consent for adoption"),
        ),
        migrations.AddField(
            model_name='pet',
            name='reunited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='reunited_with_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunited_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['found_date', 'adoption_status'], name='pets_pet_found_d_8c3f75_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['current_location_type', 'current_location_id'], name='pets_pet_current_ec9d40_idx'),
        ),
    ]
