# Generated by Django 5.2.8 on 2025-12-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_medical_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='pets.category'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='reunited_with_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunited_pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='petimage',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['adoption_status'], name='pets_pet_adoptio_ffb5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['category'], name='pets_pet_categor_b2e412_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['created_at'], name='pets_pet_created_b037d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['found_date', 'adoption_status'], name='pets_pet_found_d_8c3f75_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['current_location_type', 'current_location_id'], name='pets_pet_current_ec9d40_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['pet', '-created_at'], name='pets_medica_pet_id_3391c1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['health_status'], name='pets_medica_health__8a4e72_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['vaccination_status'], name='pets_medica_vaccina_5cff66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionapplication',
            unique_together={('pet', 'applicant')},
        ),
    ]
