# Generated by Django 5.2.8 on 2025-12-02 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_current_location_id_pet_current_location_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Under Treatment', 'Under Treatment'), ('Recovering', 'Recovering'), ('Chronic Condition', 'Chronic Condition'), ('Critical', 'Critical')], default='Healthy', help_text='Current health status of the pet', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, null=True)),
                ('vaccination_status', models.CharField(choices=[('Up to Date', 'Up to Date'), ('Partially Vaccinated', 'Partially Vaccinated'), ('Not Vaccinated', 'Not Vaccinated'), ('Unknown', 'Unknown')], default='Unknown', help_text='Vaccination status', max_length=50)),
                ('last_vaccination_date', models.DateField(blank=True, null=True)),
                ('next_vaccination_due', models.DateField(blank=True, null=True)),
                ('vaccination_notes', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Previous medical conditions and treatments', null=True)),
                ('current_medications', models.TextField(blank=True, help_text='Current medications and dosages', null=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Chronic health conditions', null=True)),
                ('veterinarian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('veterinarian_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_spayed_neutered', models.BooleanField(default=False)),
                ('spay_neuter_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional medical notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checkup_date', models.DateField(blank=True, null=True)),
                ('next_checkup_due', models.DateField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pet', '-created_at'], name='pets_medica_pet_id_3391c1_idx'), models.Index(fields=['health_status'], name='pets_medica_health__8a4e72_idx'), models.Index(fields=['vaccination_status'], name='pets_medica_vaccina_5cff66_idx')],
            },
        ),
    ]
