# Generated by Django 5.2.8 on 2025-12-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='distinguishing_marks',
            field=models.TextField(blank=True, help_text='Distinguishing marks or features', null=True),
        ),
    ]
