# Generated by Django 5.2.8 on 2025-12-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='location_map_url',
            field=models.URLField(blank=True, help_text='Google Maps or other map service URL', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='tag_registration_number',
            field=models.CharField(blank=True, help_text='Tag ID, Registration Number, or License Number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
