# Generated by Django 5.2.8 on 2025-12-07 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        ('pets', '0004_add_weight_tag_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('claim', 'Claim'), ('adoption', 'Adoption')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('pending_owner', 'Pending Owner Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner_approved_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests', to='pets.pet')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pet', 'status'], name='chats_chatr_pet_id_15cfd8_idx'), models.Index(fields=['requester', 'status'], name='chats_chatr_request_d3fd5b_idx'), models.Index(fields=['owner', 'status'], name='chats_chatr_owner_i_c34c77_idx')],
            },
        ),
    ]
