# Generated by Django 5.2.8 on 2025-12-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Target user (may be null initially, admin will set during verification)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='verified_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who verified/accepted this chat request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='chats.chatrequest'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='admin_verification_room',
            field=models.ForeignKey(blank=True, help_text='Chat room between admin and requester for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='chats.chatroom'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='final_chat_room',
            field=models.ForeignKey(blank=True, help_text='Final chat room between both users (admin can also join)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_chat_requests', to='chats.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['requester', 'status'], name='chats_chatr_request_d3fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['target', 'status'], name='chats_chatr_target__ecd6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['status'], name='chats_chatr_status_073ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chats_messa_room_id_08487d_idx'),
        ),
    ]
