# Generated by Django 5.2.8 on 2025-12-17 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_add_chatroom_fields'),
        ('pets', '0004_add_weight_tag_location_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatrequest',
            name='chats_chatr_pet_id_15cfd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatrequest',
            name='chats_chatr_owner_i_c34c77_idx',
        ),
        # Removed AlterUniqueTogether since target can be null
        migrations.AddField(
            model_name='chatrequest',
            name='admin_verification_room',
            field=models.ForeignKey(blank=True, help_text='Chat room between admin and requester for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests', to='chats.chatroom'),
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='final_chat_room',
            field=models.ForeignKey(blank=True, help_text='Final chat room between both users (admin can also join)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_chat_requests', to='chats.chatroom'),
        ),
        # Target field may already exist - check before adding
        migrations.RunSQL(
            sql="ALTER TABLE chats_chatrequest ADD COLUMN IF NOT EXISTS target_id INTEGER REFERENCES users_user(id) ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE chats_chatrequest DROP COLUMN IF EXISTS target_id;",
        ),
        migrations.AddField(
            model_name='chatrequest',
            name='user_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_room', to='chats.chatrequest'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('admin_verifying', 'Admin Verifying - Chat with Admin'), ('admin_approved', 'Admin Approved - Ready to Connect Users'), ('active', 'Active Chat'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['target', 'status'], name='chats_chatr_target__ecd6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='chatrequest',
            index=models.Index(fields=['status'], name='chats_chatr_status_073ff7_idx'),
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chatrequest',
            name='owner_approved_at',
        ),
    ]
