# Generated by Django 5.2.8 on 2025-12-17 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_remove_chatrequest_chats_chatr_pet_id_15cfd8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='target',
            field=models.ForeignKey(blank=True, help_text='Target user (may be null initially, admin will set during verification)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_requests_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
