# Generated by Django 5.2.8 on 2025-12-18 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_add_image_and_is_deleted_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrequest',
            name='verified_by_admin',
            field=models.ForeignKey(blank=True, help_text='Admin who verified/accepted this chat request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_chat_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
