# Generated by Django 5.2.8 on 2025-12-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardstats',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dashboard_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['admin', 'created_at'], name='adminpanel__admin_i_81b5c7_idx'),
        ),
        migrations.AddIndex(
            model_name='adminlog',
            index=models.Index(fields=['model_type', 'object_id'], name='adminpanel__model_t_0ed5c4_idx'),
        ),
    ]
