# Generated by Django 5.2.8 on 2025-12-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardstats',
            name='reunited_pets',
            field=models.IntegerField(default=0),
        ),
    ]
