# Generated by Django 5.2.8 on 2025-12-01 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pets', models.IntegerField(default=0)),
                ('pending_pets', models.IntegerField(default=0)),
                ('found_pets', models.IntegerField(default=0)),
                ('lost_pets', models.IntegerField(default=0)),
                ('available_pets', models.IntegerField(default=0)),
                ('adopted_pets', models.IntegerField(default=0)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('pending_applications', models.IntegerField(default=0)),
                ('total_chats', models.IntegerField(default=0)),
                ('active_chats', models.IntegerField(default=0)),
                ('pending_chat_requests', models.IntegerField(default=0)),
                ('pets_last_7_days', models.IntegerField(default=0)),
                ('users_last_7_days', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Statistics',
                'get_latest_by': 'last_updated',
            },
        ),
    ]
