# Generated by Django 5.2.8 on 2025-12-24 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('shelter', 'Shelter'), ('sub_admin', 'Sub Admin'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20)),
                ('admin_level', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sub_admin', 'Sub Admin')], help_text='Admin hierarchy level', max_length=20, null=True)),
                ('region', models.CharField(blank=True, help_text='Region assigned to sub-admin', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_volunteer', models.BooleanField(default=False)),
                ('is_shelter_provider', models.BooleanField(default=False)),
                ('volunteer_verified', models.BooleanField(default=False)),
                ('shelter_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('pincode', models.CharField(max_length=10)),
                ('region', models.CharField(help_text='Region for sub-admin', max_length=255)),
                ('organization', models.CharField(blank=True, help_text='Organization name (optional)', max_length=255, null=True)),
                ('verification_pin', models.CharField(max_length=6)),
                ('pin_sent_at', models.DateTimeField(auto_now_add=True)),
                ('pin_expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_registrations',
                'indexes': [models.Index(fields=['email'], name='admin_regis_email_2b0cba_idx'), models.Index(fields=['verification_pin'], name='admin_regis_verific_68c4e6_idx'), models.Index(fields=['is_verified'], name='admin_regis_is_veri_edd67f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AllowedAdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for reference', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_admin_emails_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowed_admin_emails',
            },
        ),
        migrations.CreateModel(
            name='FeedingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feeding_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feeding_points',
            },
        ),
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('rescuer', 'Rescuer'), ('feeder', 'Feeder'), ('transporter', 'Transporter'), ('volunteer', 'Volunteer')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Why do you want this role?')),
                ('experience', models.TextField(blank=True, help_text='Your experience with animals')),
                ('availability', models.CharField(blank=True, help_text='When are you available?', max_length=200)),
                ('resources', models.TextField(blank=True, help_text='What resources can you provide?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Request',
                'verbose_name_plural': 'Role Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_capacity', models.IntegerField(help_text='Total number of pets that can be accommodated')),
                ('current_occupancy', models.IntegerField(default=0)),
                ('area_sqft', models.IntegerField(help_text='Total area in square feet')),
                ('accepts_feeding', models.BooleanField(default=False, help_text='Accepts feeding data from users')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='List of facilities available')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shelters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shelters',
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(help_text='What food was provided')),
                ('feeding_date', models.DateField()),
                ('number_of_pets', models.IntegerField(default=1)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs')),
                ('notes', models.TextField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='users.feedingpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='users.shelter')),
            ],
            options={
                'db_table': 'feeding_records',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('can_provide_shelter', models.BooleanField(default=False)),
                ('shelter_capacity', models.IntegerField(default=0, help_text='Number of pets they can accommodate')),
                ('shelter_area_sqft', models.IntegerField(default=0, help_text='Shelter area in square feet')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_volunteers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_volunteer', 'volunteer_verified'], name='users_is_volu_c355e6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_shelter_provider', 'shelter_verified'], name='users_is_shel_2bf408_idx'),
        ),
        migrations.AddIndex(
            model_name='allowedadminemail',
            index=models.Index(fields=['email'], name='allowed_adm_email_de9475_idx'),
        ),
        migrations.AddIndex(
            model_name='allowedadminemail',
            index=models.Index(fields=['is_active'], name='allowed_adm_is_acti_5850fc_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingpoint',
            index=models.Index(fields=['is_active', 'city'], name='feeding_poi_is_acti_90fa9b_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['is_verified', 'city'], name='shelters_is_veri_f8edcc_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['accepts_feeding'], name='shelters_accepts_a85050_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['feeding_date', 'user'], name='feeding_rec_feeding_291b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['feeding_point', 'feeding_date'], name='feeding_rec_feeding_046872_idx'),
        ),
    ]
