# Generated by Django 5.2.8 on 2025-12-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('shelter', 'Shelter'), ('rescuer', 'Rescuer'), ('feeder', 'Feeder'), ('transporter', 'Transporter'), ('sub_admin', 'Sub Admin'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
