# Generated by Django 5.2.8 on 2025-12-01 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_fix_user_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feeding_points',
            },
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.TextField(help_text='What food was provided')),
                ('feeding_date', models.DateField()),
                ('number_of_pets', models.IntegerField(default=1)),
                ('photos', models.JSONField(blank=True, default=list, help_text='List of photo URLs')),
                ('notes', models.TextField(blank=True, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'feeding_records',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_capacity', models.IntegerField(help_text='Total number of pets that can be accommodated')),
                ('current_occupancy', models.IntegerField(default=0)),
                ('area_sqft', models.IntegerField(help_text='Total area in square feet')),
                ('accepts_feeding', models.BooleanField(default=False, help_text='Accepts feeding data from users')),
                ('facilities', models.JSONField(blank=True, default=list, help_text='List of facilities available')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shelters',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.IntegerField(default=0)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('can_provide_shelter', models.BooleanField(default=False)),
                ('shelter_capacity', models.IntegerField(default=0, help_text='Number of pets they can accommodate')),
                ('shelter_area_sqft', models.IntegerField(default=0, help_text='Shelter area in square feet')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'volunteers',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='is_shelter_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='shelter_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='volunteer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('shelter', 'Shelter'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_volunteer', 'volunteer_verified'], name='users_is_volu_c355e6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_shelter_provider', 'shelter_verified'], name='users_is_shel_2bf408_idx'),
        ),
        migrations.AddField(
            model_name='feedingpoint',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feeding_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='feeding_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='users.feedingpoint'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shelter',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shelters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='users.shelter'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_volunteers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feedingpoint',
            index=models.Index(fields=['is_active', 'city'], name='feeding_poi_is_acti_90fa9b_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['is_verified', 'city'], name='shelters_is_veri_f8edcc_idx'),
        ),
        migrations.AddIndex(
            model_name='shelter',
            index=models.Index(fields=['accepts_feeding'], name='shelters_accepts_a85050_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['feeding_date', 'user'], name='feeding_rec_feeding_291b5d_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['feeding_point', 'feeding_date'], name='feeding_rec_feeding_046872_idx'),
        ),
    ]
