# Generated by Django 5.2.8 on 2025-12-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='requested_role',
            field=models.CharField(choices=[('rescuer', 'Rescuer'), ('feeder', 'Feeder'), ('transporter', 'Transporter'), ('volunteer', 'General Volunteer'), ('shelter', 'Shelter Provider')], max_length=50),
        ),
    ]
