# Generated by Django 5.2.8 on 2025-12-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedingpoint_feedingrecord_shelter_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('sub_admin', 'Sub Admin')], help_text='Admin hierarchy level', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, help_text='Region assigned to sub-admin', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('volunteer', 'Volunteer'), ('shelter', 'Shelter'), ('sub_admin', 'Sub Admin'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='AdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('pincode', models.CharField(max_length=10)),
                ('region', models.CharField(help_text='Region for sub-admin', max_length=255)),
                ('organization', models.CharField(blank=True, help_text='Organization name (optional)', max_length=255, null=True)),
                ('verification_pin', models.CharField(max_length=6)),
                ('pin_sent_at', models.DateTimeField(auto_now_add=True)),
                ('pin_expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_registrations',
                'indexes': [models.Index(fields=['email'], name='admin_regis_email_2b0cba_idx'), models.Index(fields=['verification_pin'], name='admin_regis_verific_68c4e6_idx'), models.Index(fields=['is_verified'], name='admin_regis_is_veri_edd67f_idx')],
            },
        ),
    ]
