# Generated by Django 5.2.8 on 2025-12-02 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_admin_level_user_region_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('rescuer', 'Rescuer'), ('feeder', 'Feeder'), ('transporter', 'Transporter'), ('volunteer', 'Volunteer')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Why do you want this role?')),
                ('experience', models.TextField(blank=True, help_text='Your experience with animals')),
                ('availability', models.CharField(blank=True, help_text='When are you available?', max_length=200)),
                ('resources', models.TextField(blank=True, help_text='What resources can you provide?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_role_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Request',
                'verbose_name_plural': 'Role Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
