# Generated by Django 5.2.8 on 2025-12-02 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rolerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedAdminEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional name for reference', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_admin_emails_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'allowed_admin_emails',
                'indexes': [models.Index(fields=['email'], name='allowed_adm_email_de9475_idx'), models.Index(fields=['is_active'], name='allowed_adm_is_acti_5850fc_idx')],
            },
        ),
    ]
