// SafetyTipsData.js
// Data for Animal Safety Tips section
import {
  Dog,
  Cat,
  Cow,
  Camel,
  Sheep,
  Bird,
  Rabbit,
  Shield,
  PawPrint,
} from 'lucide-react';

export const safetyTipsData = [
  {
    key: 'dogs',
    name: 'Dogs',
    icon: Dog,
    color: 'bg-gradient-to-br from-orange-100 via-white to-mint-100',
    image: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=600&q=80',
    tips: [
      'Keep ID collar & microchip',
      'Regular vaccinations',
      'Clean water & balanced diet',
      'Avoid heat exposure',
      'Keep leashes in public places',
      'Emergency vet contact ready',
    ],
    link: '/care/dogs',
  },
  {
    key: 'cats',
    name: 'Cats',
    icon: Cat,
    color: 'bg-gradient-to-br from-mint-100 via-white to-orange-100',
    image: 'https://images.unsplash.com/photo-1518715308788-300e1e1bdfb0?w=600&q=80',
    tips: [
      'Safe indoor environment',
      'Keep windows & balconies secured',
      'Maintain clean litter',
      'Provide scratching posts',
      'Regular deworming',
      'Handle outdoor access carefully',
    ],
    link: '/care/cats',
  },
  {
    key: 'cows',
    name: 'Cows / Buffaloes',
    icon: Cow,
    color: 'bg-gradient-to-br from-cream-100 via-white to-blue-100',
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&q=80',
    tips: [
      'Provide clean shelter',
      'Avoid overcrowding',
      'Regular hoof checks',
      'Always have clean water',
      'Proper fodder diet',
      'Veterinary checkups frequently',
    ],
    link: '/care/cows',
  },
  {
    key: 'camels',
    name: 'Camels',
    icon: Camel,
    color: 'bg-gradient-to-br from-orange-50 via-white to-mint-100',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&q=80',
    tips: [
      'Shade during hot hours',
      'Sufficient water intake',
      'Regular hoof & joint inspection',
      'Avoid overloading',
      'Gentle, humane handling',
      'Proper resting intervals',
    ],
    link: '/care/camels',
  },
  {
    key: 'goats',
    name: 'Goats / Sheep',
    icon: Sheep,
    color: 'bg-gradient-to-br from-mint-100 via-white to-cream-100',
    image: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?w=600&q=80',
    tips: [
      'Protect from rain/cold',
      'Avoid damp floors',
      'Regular vaccination',
      'Check for parasites',
      'Provide space for movement',
      'Balanced mineral diet',
    ],
    link: '/care/goats',
  },
  {
    key: 'birds',
    name: 'Birds',
    icon: Bird,
    color: 'bg-gradient-to-br from-blue-100 via-white to-mint-100',
    image: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?w=600&q=80',
    tips: [
      'Keep cages clean & hygienic',
      'Avoid toxic fumes & Teflon pans',
      'Fresh water daily',
      'Safe perches',
      'Protect from predators',
      'Do not expose to loud noises',
    ],
    link: '/care/birds',
  },
  {
    key: 'rabbits',
    name: 'Rabbits / Small Pets',
    icon: Rabbit,
    color: 'bg-gradient-to-br from-cream-100 via-white to-mint-100',
    image: 'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=600&q=80',
    tips: [
      'Keep indoors in safe enclosures',
      'Avoid extreme temperatures',
      'Provide chew-safe toys',
      'Clean bedding',
      'Handle gently (support spine)',
      'Regular grooming',
    ],
    link: '/care/rabbits',
  },
  {
    key: 'general',
    name: 'General Animal Safety',
    icon: Shield,
    color: 'bg-gradient-to-br from-blue-50 via-white to-orange-50',
    image: 'https://images.unsplash.com/photo-1465101178521-c1a4c8a0f8d9?w=600&q=80',
    tips: [
      'Never harm or abuse animals',
      'Provide clean water & shade',
      'Report injured animals immediately',
      'Maintain vaccination schedules',
      'Proper identification (tags/microchip)',
      'Keep emergency vet numbers',
    ],
    link: '/care/general',
  },
];
