# Generated by Django 5.2.8 on 2025-12-02 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('vaccination', 'Vaccination Guide'), ('first_aid', 'First Aid Basics'), ('microchipping', 'Microchipping Info'), ('general', 'General Health')], max_length=50)),
                ('content', models.TextField()),
                ('short_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_resources/')),
                ('external_link', models.URLField(blank=True, help_text='Link to external resource if applicable')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Resource',
                'verbose_name_plural': 'Health Resources',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('ngo', models.CharField(max_length=200)),
                ('ngo_contact', models.CharField(blank=True, max_length=20)),
                ('ngo_email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField(blank=True)),
                ('registration_link', models.URLField(blank=True)),
                ('max_capacity', models.IntegerField(default=100, help_text='Maximum number of pets that can be vaccinated')),
                ('current_registrations', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_camps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccination Camp',
                'verbose_name_plural': 'Vaccination Camps',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(help_text='Dog, Cat, etc.', max_length=50)),
                ('pet_age', models.CharField(blank=True, max_length=20)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_registrations', to=settings.AUTH_USER_MODEL)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='health.vaccinationcamp')),
            ],
            options={
                'verbose_name': 'Camp Registration',
                'verbose_name_plural': 'Camp Registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('camp', 'user', 'pet_name')},
            },
        ),
    ]
