# Generated by Django 5.2.8 on 2025-12-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camp_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthresource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationcamp',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_camps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campregistration',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='health.vaccinationcamp'),
        ),
        migrations.AlterUniqueTogether(
            name='campregistration',
            unique_together={('camp', 'user', 'pet_name')},
        ),
    ]
